FROM node:lts-alpine

WORKDIR /usr/src/app

# Install app dependencies
# A wildcard is used to ensure both package.json AND package-lock.json are copied
# where available (npm@5+)
COPY package*.json ./

RUN npm install
# If you are building your code for production
# RUN npm ci --only=production
# Bundle app source
COPY . .

ENV DATABASE_URL mongodb+srv://staging:staging@cluster0.khadd.mongodb.net/staging?retryWrites=true&w=majority

ENV JWT_SECRET_KEY 'Penguin'
ENV PORT 8080

EXPOSE 8080

CMD ["npm", "run", "start:dev"]