FROM node:lts-alpine

WORKDIR /usr/src/app

# Install app dependencies
# A wildcard is used to ensure both package.json AND package-lock.json are copied
# where available (npm@5+)
COPY package*.json ./

RUN npm install
# If you are building your code for production
# RUN npm ci --only=production
# Bundle app source
COPY . .

ENV DATABASE_URL mongodb://root:2021@localhost:27017/vod?authSource=admin&readPreference=primary&appname=MongoDB%20Compass&ssl=false 
ENV PORT 5000

EXPOSE 5000

CMD ["npm", "run", "start:dev"]