# .github/workflows/git-sync.yml
name: Mirror Branches

on: push

jobs:
  git-sync:
    runs-on: ubuntu-latest
    steps:
      - name: git-sync
        uses: wei/git-sync@v3
        with:
          GIT_DISCOVERY_ACROSS_FILESYSTEM: 1
          source_repo: "https://username:personal_access_token@github.com/username/repository.git"
          source_repo: 'git@github.com:samayun/penguin.js.git'
          source_branch: 'master'
          destination_repo: 'git@github.com:samayun/mirror-test.git'
          destination_branch: 'master'
          ssh_private_key: ${{ secrets.SSH_PRIVATE_KEY }} # optional
          source_ssh_private_key: ${{ secrets.SOURCE_SSH_PRIVATE_KEY }} # optional, will override `SSH_PRIVATE_KEY`
          destination_ssh_private_key: ${{ secrets.DESTINATION_SSH_PRIVATE_KEY }} # optional, will override `SSH_PRIVATE_KEY`

