const { host, port } = require('./config/server');
const { API_ROUTE_PREFIX } = require('./config/api');

const swaggerAutogen = require('./app/modules/swagger/penguin-swagger-autogen');

const doc = {
    info: {
        version: '1.0.1',
        title: 'Penguin API',
        description: 'Documentation automatically generated by the <b>penguin-swagger-autogen</b> module.'
    },
    host: `${host}:${port}`,
    basePath: API_ROUTE_PREFIX,
    schemes: ['http', 'https'],
    consumes: ['application/json'],
    produces: ['application/json'],
    tags: [
        {
            name: 'User',
            description: 'Endpoints'
        }
    ]
};

const handlers = require('./modules')();

const outputFile = './app/modules/swagger/output/swagger_output.json';

const endpointRoutes = handlers.routes;

const semibasePath = handlers.routers;

swaggerAutogen()(outputFile, endpointRoutes, doc, semibasePath).then(generation => {
    if (generation.success) {
        console.log('All routes of application \n', Object.keys(generation.data.paths));
    }
});
