FROM node:lts-slim

ENV NODE_ENV=development

USER node

RUN mkdir -p /home/node/app

WORKDIR /home/node/app

# Install app dependencies
# A wildcard is used to ensure both package.json AND package-lock.json are copied
# where available (npm@5+)
COPY package*.json ./

# RUN npm install -g npm@latest

RUN npm install
# If you are building your code for production
# RUN npm ci --only=production
# Bundle app source
COPY . .

ENV HOST penguin.localhost

ENV DATABASE_URL mongodb://admin:password@db:27017/admin
# ENV PORT 1000

EXPOSE 1000

CMD ["npm", "run", "dev"]