/* eslint-disable no-console */
const { host, port } = require('./config/server');
const { apiRoutePrefix } = require('./config/api');

const swaggerAutogen = require('./app/modules/swagger/penguin-swagger-autogen');

const doc = {
  info: {
    version: '1.0.1',
    title: 'Penguin API',
    // eslint-disable-next-line max-len
    description:
      'Documentation automatically generated by the <b>penguin-swagger-autogen</b> module.',
  },
  host: `${host.replace('http://', '')}:${port}`,
  basePath: apiRoutePrefix,
  schemes: ['http', 'https'],
  consumes: ['application/json'],
  produces: ['application/json'],
  tags: [
    {
      name: 'User',
      description: 'Endpoints',
    },
  ],
};

console.log(`Documenting for ${host}:${port}${apiRoutePrefix}`);
const handlers = require('./modules')();

const outputFile = './app/modules/swagger/output/swagger_output.json';

const endpointRoutes = handlers.routes;

const semibasePath = handlers.routers;

swaggerAutogen()(outputFile, endpointRoutes, doc, semibasePath).then(generation => {
  if (generation.success) {
    console.log('All routes of application \n', Object.keys(generation.data.paths));
  }
});
