name: Mirror to Gitlab

on: [push]

jobs:
  gitlab:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: pixta-dev/repository-mirroring-action@v1
        with:
          target_repo_url: git@github.com:samayun/mirror-test.git
          ssh_private_key: ${{ secrets.GITLAB_SSH_KEY }}
